# Generated by Django 5.2.1 on 2026-01-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("belege", "0048_remove_beleg_bundesland_remove_kregion_bundesland_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sigle",
            fields=[
                (
                    "sigle",
                    models.CharField(
                        help_text="Sigle",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Sigle",
                    ),
                ),
                ("name", models.CharField(help_text="Name", verbose_name="Name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bl", "Bundesland"),
                            ("gr", "Großregion"),
                            ("kr", "Kleinregion"),
                            ("ort", "Ort"),
                        ],
                        verbose_name="Art der Sigle",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(blank=True, null=True, verbose_name="Koordinaten"),
                ),
                (
                    "geonames",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Geonames URL",
                    ),
                ),
                (
                    "bl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="has_bl",
                        to="siglen.sigle",
                    ),
                ),
                (
                    "gr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="has_gr",
                        to="siglen.sigle",
                    ),
                ),
                (
                    "kr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="has_kr",
                        to="siglen.sigle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BelegSigle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corresp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@corrsp"
                    ),
                ),
                (
                    "resp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="@resp"
                    ),
                ),
                (
                    "beleg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="belege.beleg",
                        verbose_name="Beleg",
                    ),
                ),
                (
                    "sigle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siglen.sigle",
                        verbose_name="Sigle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beleg-Sigle",
                "verbose_name_plural": "Belege-Siglen",
                "ordering": ["sigle"],
            },
        ),
    ]
