# Generated by Django 5.2.1 on 2026-01-05 09:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siglen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sigle",
            options={
                "ordering": ["sigle"],
                "verbose_name": "Sigle",
                "verbose_name_plural": "Siglen",
            },
        ),
        migrations.AddField(
            model_name="sigle",
            name="orig_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
                verbose_name="Original Ortsnamen",
            ),
        ),
    ]
