# Generated by Django 5.2.1 on 2026-01-05 10:07

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siglen", "0002_alter_sigle_options_sigle_orig_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sigle",
            name="orig_names",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                size=None,
                verbose_name="Original Ortsnamen",
            ),
        ),
    ]
