# Generated by Django 5.2.1 on 2025-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0009_remove_tag_emoji"),
        ("belege", "0044_annotation_source_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="belege",
                to="annotations.tag",
                verbose_name="Belege",
            ),
        ),
    ]
