# Generated by Django 5.2.1 on 2026-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0010_alter_annotation_options_alter_autor_artikel_options_and_more",
        ),
        ("belege", "0046_beleg_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beleg",
            name="collection",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collection",
                related_name="beleg",
                to="annotations.collection",
                verbose_name="Collection",
            ),
        ),
    ]
