# Generated by Django 5.2.1 on 2026-01-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0047_alter_beleg_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="bundesland",
        ),
        migrations.RemoveField(
            model_name="kregion",
            name="bundesland",
        ),
        migrations.RemoveField(
            model_name="ort",
            name="bundesland",
        ),
        migrations.RemoveField(
            model_name="gregion",
            name="bundesland",
        ),
        migrations.RemoveField(
            model_name="georelationbundesland",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="georelationbundesland",
            name="beleg",
        ),
        migrations.RemoveField(
            model_name="georelationgregion",
            name="beleg",
        ),
        migrations.RemoveField(
            model_name="georelationgregion",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="gregion",
        ),
        migrations.RemoveField(
            model_name="georelationkregion",
            name="beleg",
        ),
        migrations.RemoveField(
            model_name="georelationkregion",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="kregion",
        ),
        migrations.RemoveField(
            model_name="georelationort",
            name="beleg",
        ),
        migrations.RemoveField(
            model_name="georelationort",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="ort",
        ),
        migrations.RemoveField(
            model_name="ort",
            name="gregion",
        ),
        migrations.RemoveField(
            model_name="kregion",
            name="gregion",
        ),
        migrations.RemoveField(
            model_name="ort",
            name="kregion",
        ),
    ]
