# Generated by Django 5.2.1 on 2026-01-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0048_remove_beleg_bundesland_remove_kregion_bundesland_and_more"),
        ("siglen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="sigle",
            field=models.ManyToManyField(
                blank=True,
                through="siglen.BelegSigle",
                to="siglen.sigle",
                verbose_name="Sigle",
            ),
        ),
        migrations.DeleteModel(
            name="BundesLand",
        ),
        migrations.DeleteModel(
            name="GeoRelationBundesland",
        ),
        migrations.DeleteModel(
            name="GeoRelationGregion",
        ),
        migrations.DeleteModel(
            name="GeoRelationKregion",
        ),
        migrations.DeleteModel(
            name="GeoRelationOrt",
        ),
        migrations.DeleteModel(
            name="GRegion",
        ),
        migrations.DeleteModel(
            name="KRegion",
        ),
        migrations.DeleteModel(
            name="Ort",
        ),
    ]
