# Generated by Django 5.2.1 on 2026-01-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "annotations",
            "0010_alter_annotation_options_alter_autor_artikel_options_and_more",
        ),
        ("belege", "0049_beleg_sigle_delete_bundesland_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beleg",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                related_name="belege",
                to="annotations.tag",
                verbose_name="Tag",
            ),
        ),
    ]
