# Generated by Django 5.2.1 on 2026-09-16 07:23

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0068_beleg_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beleg",
            name="ref_type_dbo",
        ),
        migrations.RemoveField(
            model_name="beleg",
            name="ref_type_sni",
        ),
        migrations.AddField(
            model_name="citation",
            name="ref",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores tei:ref with different @type values",
                null=True,
                verbose_name="./tei:ref[not(@type='fragebogenNummer')]",
            ),
        ),
    ]
