# Generated by Django 5.2.1 on 2026-09-17 05:00

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0069_remove_beleg_ref_type_dbo_remove_beleg_ref_type_sni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="verweislemma",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores tei:form with @type 'verweisLemma'",
                null=True,
                verbose_name="tei:form[@type='verweisLemma']",
            ),
        ),
        migrations.AlterField(
            model_name="citation",
            name="ref",
            field=django_jsonform.models.fields.JSONField(
                blank=True,
                help_text="stores tei:ref with different @type values",
                null=True,
                verbose_name="tei:ref",
            ),
        ),
    ]
