# Generated by Django 5.2.1 on 2026-09-17 06:31

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0070_beleg_verweislemma_alter_citation_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="figure",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=250, null=True),
                blank=True,
                default=list,
                help_text="stores ./tei:figure/tei:note",
                size=None,
                verbose_name="Bilddatei",
            ),
        ),
    ]
