# Generated by Django 5.2.1 on 2026-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0071_beleg_figure"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="quelle_number",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Nummer (Quelle)"
            ),
        ),
    ]
