# Generated by Django 5.2.1 on 2026-09-21 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0072_beleg_quelle_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DboeXmlFile",
            fields=[
                (
                    "dboe_id",
                    models.CharField(
                        help_text="The filename of the DBÖ-XML-File",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="DBÖ ID (Dateiname)",
                    ),
                ),
                (
                    "nr_belege",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Anzahl der tei:entry Einträge",
                        null=True,
                        verbose_name="Anzahl der Einträge",
                    ),
                ),
                (
                    "belege_imported",
                    models.BooleanField(
                        default=False,
                        help_text="Wurden die zughörigen Belege bereits importiert?",
                        verbose_name="Belege importiert",
                    ),
                ),
            ],
            options={
                "verbose_name": "DBÖ-XML Datei",
                "verbose_name_plural": "DBÖ-XML Dateien",
                "ordering": ["dboe_id"],
            },
        ),
        migrations.AddField(
            model_name="beleg",
            name="xml_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="belege.dboexmlfile",
                verbose_name="Original XML-Datei",
            ),
        ),
    ]
