# Generated by Django 5.2.1 on 2026-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belege", "0073_dboexmlfile_beleg_xml_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dboexmlfile",
            name="belege_indexed",
            field=models.BooleanField(
                default=False,
                help_text="Wurden die zughörigen Belege bereits indexiert",
                verbose_name="Belege indexiert",
            ),
        ),
        migrations.AddField(
            model_name="dboexmlfile",
            name="belege_linked",
            field=models.BooleanField(
                default=False,
                help_text="Wurden die zughörigen Belege bereits mit Siglen verknüpft",
                verbose_name="Belege lokalisiert",
            ),
        ),
    ]
