# Generated by Django 5.2.1 on 2025-12-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0008_auto_20251211_1614"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="emoji",
        ),
    ]
