# Generated by Django 5.2.1 on 2026-01-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0009_remove_tag_emoji"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annotation",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="autor_artikel",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="edit_of_article",
            options={
                "ordering": ["id"],
                "verbose_name": "Edit of Article",
                "verbose_name_plural": "Edits of Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="es_document",
            options={"ordering": ["es_id"]},
        ),
        migrations.AlterModelOptions(
            name="lemma",
            options={
                "ordering": ["id"],
                "verbose_name": "Lemma",
                "verbose_name_plural": "Lemmata",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
